name: waterreminder
description: Water reminder App.
publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animations: ^2.0.0
  flutter_bloc: ^7.0.0
  rxdart: ^0.26.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  firebase_database: ^10.2.2
  flutter_localization: ^0.1.11
  inspection: ^0.0.13
  syncfusion_flutter_gauges: ^21.2.8
  google_maps_flutter: ^2.0.4
  google_fonts: ^5.0.0
  carousel_slider: ^4.0.0
  flutter_svg: ^2.0.6
  animated_text_kit: ^4.2.2
  lottie: ^2.4.0
  location: ^4.4.0
  geolocator: ^9.0.2
  permission_handler: ^10.3.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: AppSymbols
      fonts:
      - asset: fonts/AppSymbols.ttf

    - family: Comfortaa
      fonts:
      - asset: fonts/Comfortaa-Regular.ttf

      - asset: fonts/Comfortaa-Light.ttf
        weight: 300
      
      - asset: fonts/Comfortaa-Medium.ttf
        weight: 500

      - asset: fonts/Comfortaa-SemiBold.ttf
        weight: 600
      
      - asset: fonts/Comfortaa-Bold.ttf
        weight: 700

